### ISSUE TITLE
Could you add links to the datasets?

### ISSUE THREAD

**Issue by Ranapop** [abdcelikkanat/grassp#1]
Hi!

Would it be possible to add links to the real-world datasets that were experimented with in the paper?

Also, any instructions on running pre-processing steps on the data (if applicable) would be appreciated.

**Comment by abdcelikkanat** [comment]
Hi @Ranapop 

I've uploaded the datasets to the repository. The edges are formatted as 'Node1, Node2, Time, State.' If the network initially contains any links, their state should be set to 1. If a link disappears at a certain time, say t1, it must be re-added with its state set to 0 and time t1. Similarly, if the link reappears at time t2, its state must be updated to 1 again for time t2, and so on.
